apiVersion: v2
name: gitlab-backup2s3
description: Kubernetes CronJob for GitLab backups to S3-compatible storage

type: application
version: 0.6.1
appVersion: "2.3.0"

icon: view-source:https://raw.githubusercontent.com/sgaunet/helmchart-helper/main/ico/helm.ico
